### PR TITLE
OPi Zero+2 -H5

### PR DESCRIPTION
**Pull request by georgep56**

### CODE REVIEW

**Comment by igorpecovnik** [comment]
Please update image (apt update & apt upgrade + reboot) to the most recent kernel.

**Comment by georgep56** [comment]
I just updated but now when I run createreport.sh I get this response to
the pull request on github:


File /home/george/testings/.git/PULLREQ_EDITMSG saved
Error creating pull request: Unprocessable Entity (HTTP 422)
A pull request already exists for
georgep56:20180827-orangepizeroplus2-h5-next.
george@orangepizeroplus2:~/testings$

**Comment by igorpecovnik** [comment]
Tools need some fine tuning ... Thanks for help!

**Comment by chwe17** [comment]
yeah, the script has still some faults. a temporarily working solution:
go to the repo, then git remote -v, it should show something like (with your username):
```
chwe17	https://github.com/chwe17/testings.git (fetch)
chwe17	https://github.com/chwe17/testings.git (push)
origin	https://github.com/armbian/testings.git (fetch)
origin	https://github.com/armbian/testings.git (push)
```
type then `git checkout 20180827-orangepizeroplus2-h5-next && git commit -A && git push -u <username> 20180827-orangepizeroplus2-h5-next` 
this should update your branch with the changes you made and then show up in this PR.

**Comment by georgep56** [comment]
OK I tried those commands (('commit -A' gave an error so I did 'commit
-a')) but it seems there is now some kind of conflict that I can't resolve.

Sorry but I'm not too familiar with git :-)

**Pull request closed without merging**
